### ISSUE TITLE
Error: Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by moooji** [Prozi/pixi-shim#10]
This simple script fails on node 12.13:

```
const PIXI = require('pixi-shim')

const app = new PIXI.Application(800, 600, { backgroundColor: 0x1099bb });
```

with these exceptions:
```
pixi-shim ❤️ dom
pixi-shim ❤️ canvas
pixi-shim ❤️ pixijs
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
    at createWhiteTexture (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/core/lib/core.js:3743:26)
    at Object.<anonymous> (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/core/lib/core.js:3779:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) undefined
/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/core/lib/core.js:3745
    context.fillStyle = 'white';
                      ^

TypeError: Cannot set property 'fillStyle' of null
    at createWhiteTexture (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/core/lib/core.js:3745:23)
    at Object.<anonymous> (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/core/lib/core.js:3779:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Volumes/Data/Workspace/touchtech/dsr-mail/node_modules/@pixi/extract/lib/extract.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

It looks like the installed dependencies are:
PixiJS 5.2.0
canvas 2.6.0

**Comment by Prozi** [comment]
@moooji Please try latest version (1.7.0) it should work ok now

**Comment by Prozi** [comment]
closing due `I think it works` and you didnt take time to check
