### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by MartinTremblay** [Prozi/pixi-shim#11]
Trying a simple case, but I'm getting a "binding" error.

```
pixi-shim ❤️ DOM
pixi-shim ❤️ Window 1024x768
/var/www/html/node-character/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /var/www/html/node-character/node_modules/node-gles/build/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/build/Debug/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/build/Release/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/out/Debug/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/Debug/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/out/Release/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/Release/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/build/default/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/compiled/10.16.2/linux/x64/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/addon-build/release/install-root/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/addon-build/debug/install-root/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/addon-build/default/install-root/nodejs_gl_binding.node
 → /var/www/html/node-character/node_modules/node-gles/lib/binding/node-v64-linux-x64/nodejs_gl_binding.node
    at bindings (/var/www/html/node-character/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/var/www/html/node-character/node_modules/node-gles/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/html/node-character/node_modules/pixi-shim/lib/node/canvas.js:9:5)
```

**Comment by Prozi** [comment]
Hello @MartinTremblay I havent seen this one yet :japanese_ogre: 

To me, looks like something with node-gles, maybe I should bump the version.
Try adding it to your projects dependencies, and report back did it help.

Regards

**Comment by Prozi** [comment]
`npm i node-gles --save` of course

**Comment by hunterorion** [comment]
I have experienced the same issue, I have installed pixi-shim using yarn 2.0 (berry) package manager. I tried adding the node-gles to my dependencies and this did not appear to resolve the issue. I would be grateful for any help or suggestions you could provide.

pixi-shim ❤️ DOM
pixi-shim ❤️ Window 1024x768
/home/orion/programming/javascript/Covert_Company/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/build/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/build/Debug/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/build/Release/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/out/Debug/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/Debug/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/out/Release/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/Release/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/build/default/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/compiled/10.15.2/linux/x64/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/addon-build/release/install-root/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/addon-build/debug/install-root/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/addon-build/default/install-root/nodejs_gl_binding.node
 → /home/orion/programming/javascript/Covert_Company/node_modules/node-gles/lib/binding/node-v64-linux-x64/nodejs_gl_binding.node
    at bindings (/home/orion/programming/javascript/Covert_Company/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/orion/programming/javascript/Covert_Company/node_modules/node-gles/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/orion/programming/javascript/Covert_Company/node_modules/pixi-shim/lib/node/canvas.js:4:41)

**Comment by Coppertine** [comment]
So after installing Visual C++ using Visual Studio 2019, I got gles installed, however. It can't find the bindings file..
```
Error: The specified module could not be found.
\\?\c:\Users\user\nodejs\raspPiProject\node_modules\node-gles\build\Release\nodejs_gl_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (c:\Users\user\nodejs\raspPiProject\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (c:\Users\user\nodejs\raspPiProject\node_modules\node-gles\dist\index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
```

**Comment by LeedaCode** [comment]
```
pixi-shim ❤️ DOM
pixi-shim ❤️ Window 1024x768
I:\check pixi.js code\pixi-shim-master\node_modules\_bindings@1.5.0@bindings\bin
dings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\build\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\build\Debug\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\build\Release\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\out\Debug\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\Debug\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\out\Release\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\Release\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\build\default\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\compiled\12.16.2\win32\x64\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\addon-build\release\install-root\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\addon-build\debug\install-root\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\addon-build\default\install-root\nodejs_gl_binding.node
 → I:\check pixi.js code\pixi-shim-master\node_modules\_node-gles@0.0.17@node-g
les\lib\binding\node-v72-win32-x64\nodejs_gl_binding.node
    at bindings (I:\check pixi.js code\pixi-shim-master\node_modules\?[4m_bindin
gs@1.5.0@bindings?[24m\bindings.js:126:9)
    at Object.<anonymous> (I:\check pixi.js code\pixi-shim-master\node_modules\?
[4m_node-gles@0.0.17@node-gles?[24m\dist\index.js:4:15)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:1
0)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:77:18)?[39m
    at Object.<anonymous> (I:\check pixi.js code\pixi-shim-master\lib\node\canva
s.js:4:41)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1156:30)?[39m {
  tries: [
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\build\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\build\\Debug\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\build\\Release\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\out\\Debug\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\Debug\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\out\\Release\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\Release\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\build\\default\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\compiled\\12.16.2\\win32\\x64\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\addon-build\\release\\install-root\\nodejs_gl_binding.node'?[39m,

    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\addon-build\\debug\\install-root\\nodejs_gl_binding.node'?[39m,
    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\addon-build\\default\\install-root\\nodejs_gl_binding.node'?[39m,

    ?[32m'I:\\check pixi.js code\\pixi-shim-master\\node_modules\\_node-gles@0.0
.17@node-gles\\lib\\binding\\node-v72-win32-x64\\nodejs_gl_binding.node'?[39m
  ]
}

```
Yes,I also encountered this problem.

**Comment by Prozi** [comment]
Can You write what version od pixi shim You installed and how? I would like the exact steps.

**Comment by hunterorion** [comment]
I used yarn package manager (2.X) to install pixi-shim version 1.8.2

**Comment by Prozi** [comment]
Hmm and you guys are using it in nodejs context? Which version and how?
